import type { ScanAnswers } from "./types";

/** (a) Series A SaaS ops-heavy builder — OPS top, qualified */
export const seriesAOpsHeavy: ScanAnswers = {
  q1: "team_26_80",
  q2: "series_a_plus",
  q3: "founder_ceo",
  q4: "b2b_saas",
  q5: ["manual_entry", "sales_followup", "content_docs"],
  q6: "more_without_hiring",
  q7: "clone_ops",
  q8: "daily",
  q9: "hours_40_100",
  q10: "live_production",
  q11: "unclear_impact",
  q12: ["internal_pilot", "coding_copilots"],
  q13: "no_time",
  q14: "modern_saas",
  q15: "dedicated_team",
  q16: "documented",
  q17: ["none"],
  q18: "this_quarter",
  q19: "dedicated_budget",
};

/** (b) Stalled prototype company — RESCUE surfaced, build lean */
export const stalledPrototype: ScanAnswers = {
  q1: "team_11_25",
  q2: "seed",
  q3: "eng_lead",
  q4: "b2b_saas",
  q5: ["content_docs"],
  q6: "shipping_speed",
  q7: "clone_engineering",
  q8: "sometimes",
  q9: "hours_10_40",
  q10: "prototype_never_shipped",
  q11: "costing_deals",
  q12: ["internal_pilot"],
  q13: "not_wired",
  q14: "modern_saas",
  q15: "no_bandwidth",
  q16: "in_heads",
  q17: ["none"],
  q18: "next_6_months",
  q19: "roi_contingent",
};

/** (c) 6-person bootstrapped team with support pain — CX top, BUY lean, nurture */
export const bootstrappedSupportPain: ScanAnswers = {
  q1: "team_1_10",
  q2: "bootstrapped",
  q3: "founder_ceo",
  q4: "b2b_saas",
  q5: ["support_tickets"],
  q6: "retention",
  q7: "clone_support",
  q8: "constantly",
  q9: "hours_under_10",
  q10: "on_roadmap",
  q11: "not_yet",
  q12: ["chatgpt_adhoc"],
  q13: "havent_tried",
  q14: "modern_saas",
  q15: "no_engineers",
  q16: "in_heads",
  q17: ["none"],
  q18: "just_exploring",
  q19: "no_budget",
};

/** (d) Scattered-data analytics-hungry company — DATA surfaced, WAIT lean */
export const scatteredDataAnalytics: ScanAnswers = {
  q1: "team_11_25",
  q2: "seed",
  q3: "ops_cs_lead",
  q4: "b2b_saas",
  q5: ["reporting", "internal_questions"],
  q6: "retention",
  q7: "clone_analyst",
  q8: "rarely",
  q9: "hours_10_40",
  q10: "not_applicable",
  q11: "dont_know",
  q12: ["nothing_formal"],
  q13: "data_mess",
  q14: "scattered",
  q15: "no_bandwidth",
  q16: "varies",
  q17: ["none"],
  q18: "next_6_months",
  q19: "roi_contingent",
};

/** (e) Soft-qualified explorer — Series A+, exploring, high readiness */
export const softQualifiedExplorer: ScanAnswers = {
  q1: "team_11_25",
  q2: "series_a_plus",
  q3: "exec",
  q4: "b2b_saas",
  q5: ["manual_entry", "reporting"],
  q6: "cost_burn",
  q7: "clone_ops",
  q8: "daily",
  q9: "hours_40_100",
  q10: "live_production",
  q11: "unclear_impact",
  q12: ["vendor_tool", "chatgpt_adhoc"],
  q13: "nobody_owns",
  q14: "modern_saas",
  q15: "dedicated_team",
  q16: "documented",
  q17: ["none"],
  q18: "just_exploring",
  q19: "roi_contingent",
};

/** (f) Established marketplace with GLUE hybrid lean */
export const marketplaceGlueHybrid: ScanAnswers = {
  q1: "team_26_80",
  q2: "established",
  q3: "ops_cs_lead",
  q4: "marketplace",
  q5: ["manual_entry", "onboarding"],
  q6: "cost_burn",
  q7: "clone_ops",
  q8: "daily",
  q9: "hours_100_plus",
  q10: "not_applicable",
  q11: "not_yet",
  q12: ["vendor_tool"],
  q13: "not_wired",
  q14: "modern_saas",
  q15: "no_bandwidth",
  q16: "in_heads",
  q17: ["none"],
  q18: "this_quarter",
  q19: "dedicated_budget",
};

/** (g) PROD-focused competitor pressure — qualified, PROD surfaced */
export const prodCompetitorPressure: ScanAnswers = {
  q1: "team_11_25",
  q2: "seed",
  q3: "founder_ceo",
  q4: "b2b_saas",
  q5: ["support_tickets"],
  q6: "revenue",
  q7: "clone_engineering",
  q8: "sometimes",
  q9: "hours_10_40",
  q10: "on_roadmap",
  q11: "costing_deals",
  q12: ["hired_owner"],
  q13: "no_time",
  q14: "modern_saas",
  q15: "dedicated_team",
  q16: "documented",
  q17: ["none"],
  q18: "this_quarter",
  q19: "roi_contingent",
};

/** (h) Foundations-first low readiness */
export const foundationsFirst: ScanAnswers = {
  q1: "team_1_10",
  q2: "bootstrapped",
  q3: "other",
  q4: "services_agency",
  q5: ["content_docs"],
  q6: "cost_burn",
  q7: "clone_sales",
  q8: "rarely",
  q9: "hours_under_10",
  q10: "not_applicable",
  q11: "not_yet",
  q12: ["nothing_formal"],
  q13: "havent_tried",
  q14: "scattered",
  q15: "no_engineers",
  q16: "varies",
  q17: ["regulated", "sensitive_data"],
  q18: "just_exploring",
  q19: "no_budget",
};

/** (i) Large team nurture — qualified stage signals but no budget */
export const largeTeamNoBudget: ScanAnswers = {
  q1: "team_80_plus",
  q2: "established",
  q3: "exec",
  q4: "ecommerce_dtc",
  q5: ["support_tickets", "onboarding"],
  q6: "retention",
  q7: "clone_support",
  q8: "constantly",
  q9: "hours_40_100",
  q10: "live_production",
  q11: "unclear_impact",
  q12: ["vendor_tool"],
  q13: "trust_outputs",
  q14: "modern_saas",
  q15: "dedicated_team",
  q16: "documented",
  q17: ["sensitive_data"],
  q18: "next_6_months",
  q19: "no_budget",
};

/** (j) CX build lean — large team with onboarding pain */
export const largeTeamCxBuild: ScanAnswers = {
  q1: "team_26_80",
  q2: "series_a_plus",
  q3: "ops_cs_lead",
  q4: "b2b_saas",
  q5: ["onboarding", "support_tickets"],
  q6: "retention",
  q7: "clone_support",
  q8: "constantly",
  q9: "hours_10_40",
  q10: "live_production",
  q11: "not_yet",
  q12: ["internal_pilot"],
  q13: "nobody_owns",
  q14: "modern_saas",
  q15: "dedicated_team",
  q16: "documented",
  q17: ["sensitive_data"],
  q18: "this_quarter",
  q19: "dedicated_budget",
};
